### ISSUE TITLE
Failed to activate the jquery-snippets package

### ISSUE THREAD

**Issue by waxidiotic** [james2doyle/atom-jquery-snippets#11] opened 2015-06-26 19:12 UTC
[Enter steps to reproduce below:]

1. Go to Packages > jquery-snippets > Toggle.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [jquery-snippets](https://github.com/james2doyle/atom-jquery-snippets) package, v1.0.0

### Stack Trace

Failed to activate the jquery-snippets package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at JquerySnippetsView.module.exports.JquerySnippetsView.initialize (/Users/alexbussey/.atom/packages/jquery-snippets/lib/jquery-snippets-view.coffee:28:32)
    at JquerySnippetsView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new JquerySnippetsView (/Users/alexbussey/.atom/packages/jquery-snippets/lib/jquery-snippets-view.coffee:12:55)
    at Object.module.exports.activate (/Users/alexbussey/.atom/packages/jquery-snippets/lib/jquery-snippets.coffee:9:40)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
```

### Commands

```
     -0:00.6.0 jquery-snippets:toggle (atom-pane.pane.active)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
jquery-snippets, v1.0.0

# Dev
No dev packages
```

**Comment by j-ro** [comment] 2015-06-27 18:32
I was able to get this working by restarting atom, fyi

**Comment by waxidiotic** [comment] 2015-06-29 21:53
I tried restarting and it happened again. I haven't tried in a few days, I'll let you know.

**Comment by waxidiotic** [comment] 2015-06-29 21:53
Nope - still happening.

**Comment by seancrater** [comment] 2015-06-30 12:51
Getting the same error after restarting.

**Comment by sitnikovalex** [comment] 2015-06-30 15:23
same error

**Comment by Lars-** [comment] 2015-07-05 11:38
Restarting worked for me.

**Comment by BaranWang** [comment] 2015-07-07 14:55
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.11
**Thrown From**: [jquery-snippets](https://github.com/james2doyle/atom-jquery-snippets) package, v1.0.0


### Stack Trace

Failed to activate the jquery-snippets package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at JquerySnippetsView.module.exports.JquerySnippetsView.initialize (/Users/baran/.atom/packages/jquery-snippets/lib/jquery-snippets-view.coffee:10:23)
  at JquerySnippetsView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new JquerySnippetsView (/Users/baran/.atom/packages/jquery-snippets/lib/jquery-snippets-view.coffee:5:3)
  at Object.module.exports.activate (/Users/baran/.atom/packages/jquery-snippets/lib/jquery-snippets.coffee:7:31)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:00.5.0 jquery-snippets:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.12
jquery-snippets, v1.0.0

# Dev
No dev packages
```

**Comment by BaranWang** [comment] 2015-07-08 13:50
进入目录packages/atom-jquery-snippets/menus/jquery-snippets.cson
修改两个command为commands
目前正常使用

My English is so poor. The function can use this packgage

**Comment by wstudios** [comment] 2015-08-18 23:39
Same error too, using the latest Atom 1.0.7. Any fix for this issue?

**Comment by waxidiotic** [comment] 2015-08-20 19:15
Still having this issue with Atom 1.0.7 on a completely different machine. Not sure why @james2doyle hasn't replied yet.

**Comment by james2doyle** [comment] 2015-08-20 19:30
@waxidiotic @wstudios try uninstalling and installing via git. I have pulled some PRs in the last couple days. These add support for the latest Atom. I have tested the plugin and it works from what I can tell. 

There is something wrong with the Atom publish 

![screen shot 2015-08-20 at 12 28 57 pm](https://cloud.githubusercontent.com/assets/1425304/9393495/228594b8-4737-11e5-813d-b6da7c74951b.png)

You can also see that all the releases are screwed up too because of this

**Comment by waxidiotic** [comment] 2015-08-20 19:48
@james2doyle great, uninstalling it and reinstalling via git and apm worked. however, now i'm stuck with both atom-jquery-snippets and jquery-snippets in the packages list, even though i uninstalled it the first time.

**Comment by james2doyle** [comment] 2015-08-20 19:57
Something is wrong. I cant seem to get this to publish at all. I keep getting the application error. I even removed the tests and it runs fine. But I cant seem to publish

**Comment by james2doyle** [comment] 2015-08-20 20:00
Looks like something is up https://github.com/atom/atom.io/issues/23

**Comment by waxidiotic** [comment] 2015-08-20 20:02
So I should leave the duplicate package installed?

**Comment by james2doyle** [comment] 2015-08-20 20:51
Maybe you can manually remove it from your Atom packages folder?

**Comment by james2doyle** [comment] 2015-08-21 21:13
I was finally able to publish the package. If you installed manually, you can delete it, and reinstall from the app.

**Closed** 2015-08-21 21:12 UTC

**Comment by asyrique** [comment] 2015-08-23 23:42
Error seems to still be occuring in version 11.0.0 (have tried uninstalling and reinstalling already.)
![image](https://cloud.githubusercontent.com/assets/5598413/9430786/b40d9d78-4a33-11e5-9cc5-6bb2ebebabf9.png)

Atom version: 1.0.7

**Comment by james2doyle** [comment] 2015-08-24 13:28
@asyrique I have been unable to get this error. Maybe try manually removing the package and installing in the app?

**Comment by waxidiotic** [comment] 2015-08-24 13:31
@james2doyle everything works for me now. thanks!

**Comment by BaranWang** [comment] 2015-08-25 02:33
@asyrique You can enter folder to `packages/atom-jquery-snippets/menus/jquery-snippets.cson`
Search `command` replace to `commands`

This scheme can make the plug can be used.

---

My English is poor, so maybe you don't understand

**Comment by faddah** [comment] 2015-09-01 01:18
this is still happening in Mac OS X 10.10.5 Yosemite, Atom Editor v.1.0.7, when trying to update from your jQuery Snippets package from 1.0.0 to 11.0.0. below is the error report i got.

![screen shot 2015-08-31 at 18 17 22](https://cloud.githubusercontent.com/assets/398378/9594171/96fab73c-500c-11e5-9e2b-742233976fb2.png)

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [jquery-snippets](https://github.com/james2doyle/atom-jquery-snippets) package, v11.0.0


### Stack Trace

Failed to activate the jquery-snippets package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at JquerySnippetsView.module.exports.JquerySnippetsView.initialize (/Users/yuetsu/.atom/packages/jquery-snippets/lib/jquery-snippets-view.coffee:10:24)
  at JquerySnippetsView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new JquerySnippetsView (/Users/yuetsu/.atom/packages/jquery-snippets/lib/jquery-snippets-view.coffee:5:3)
  at Object.module.exports.activate (/Users/yuetsu/.atom/packages/jquery-snippets/lib/jquery-snippets.coffee:7:31)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:312:60
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "irregular-keypress-sounds"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.11
atom-snippets, v0.1.1
atom-ternjs, v0.7.2
atom-wordpress, v0.3.0
autocomplete-php, v0.3.7
color-picker, v2.0.11
css-snippets, v0.8.0
drunken-php, v0.1.2
gulp-snippets, v0.6.2
html-id-class-snippets, v1.4.1
javascript-snippets, v1.0.0
jquery-snippets, v11.0.0
linter, v1.5.0
linter-csslint, v1.0.5
linter-js-standard, vundefined
linter-jshint, v1.1.5
linter-php, v1.0.3
linter-tslint, v0.3.0
minimap, v4.13.2
php-analyser, v0.2.0
project-manager, v2.0.1
project-view, v0.1.2
seti-ui, v0.8.0
wordpress-api, v1.2.1

# Dev
No dev packages
```

i suggest you re-open this issue.

best,

—  faddah
     portland, oregon, u.s.a.
